- name: Remove the teleport and teleport-ent packages
  ansible.builtin.package:
    state: absent
    name:
      - teleport
      - teleport-ent

# Only needed for kube deployments. Bot is not used on node deployments.
- name: Remove the MachineID bot
  delegate_to: "{{ teleport_executor }}"
  run_once: true
  when: auth_pods is defined
  kubernetes.core.k8s_exec:
    namespace: teleport-cluster
    pod: "{{ auth_pods.resources[0].metadata.name }}"
    command: "tctl bots rm temporary_bot"

- name: Remove the teleport files and directories
  loop:
    - /usr/local/bin/tbot
    - /usr/local/bin/tctl
    - /usr/local/bin/teleport
    - /usr/local/bin/tsh
    - /usr/local/bin/fdpass-teleport
    - /root/machine-id-temp
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
