---
# Run this once if no certs were available before
- name: Local setup
  hosts: 127.0.0.1
  connection: local
  become: false
  tasks:
    - name: Install lego
      become: "{{ ansible_distribution | string != 'MacOSX' }}" # Disable sudo for MacOSX
      ansible.builtin.package:
        name: "{{ lego_package_os_map[ansible_distribution] }}"

    - name: Create cert dir
      ansible.builtin.file:
        path: "{{ lego_path_local }}"
        state: directory
        mode: "0700"

    - name: Get the cert
      changed_when: true
      environment: "{{ letsencrypt_lego_env_vars }}"
      ansible.builtin.command:
        cmd: >-
          lego
              --server={{ letsencrypt_working_environment[letsencrypt_working_environment_choice] }}
              --email "{{ e_mail }}"
              --dns cloudflare
              --domains '*.{{ domain_name }}'
              --domains '{{ domain_name }}'
              --accept-tos
              --path "{{ lego_path_local }}"
              run

    - name: Change cert permissions
      ansible.builtin.file:
        path: "{{ lego_path_local }}"
        mode: "u=rwX,g-rwx,o-rwx"
        recurse: true
        state: directory
        owner: "{{ user_local }}"
        group: "{{ user_local }}"
