---
- name: Terraform run
  hosts: localhost
  become: false
  roles:
    - tf_simple

- name: Cluster node setup
  hosts:
    - teleport
  roles:
    - util_common
    - teleport_install
    - teleport

- name: Agent nodes setup
  hosts:
    - nodes_ssh_agent
  vars:
    teleport_semaphore_auth_host: teleport
    teleport_semaphore_auth_host_type: node
    teleport_install_teleport_agent: true # Needed by the teleport_install
  roles:
    - util_common
    - teleport_ssh_agent

- name: Agentless nodes setup
  hosts:
    - nodes_ssh_agentless
  vars:
    teleport_semaphore_auth_host: teleport
    teleport_semaphore_auth_host_type: node
  roles:
    - util_common
    - teleport_ssh_agentless
    # - teleport_ssh_agentless_simple # Broken on most distros

- name: Teleport RBAC Bootstrap
  hosts: teleport
  vars:
    teleport_semaphore_auth_host: teleport
    teleport_semaphore_auth_host_type: node
  roles:
    - util_common
    - teleport_rbac_bootstrap
