---
- name: Terraform run
  hosts: localhost
  become: false
  roles:
    - tf_kubernetes_dynamic

- name: Tasks for all hosts
  hosts: teleport, teleport_kubernetes_dynamic
  roles:
    - util_common
    - teleport_install

- name: Teleport host setup
  hosts: teleport
  roles:
    - util_common
    - teleport

- name: Kubernetes cluster setup
  hosts: teleport_kubernetes_dynamic
  roles:
    - util_common
    - k3s_install
    - teleport_kubernetes_crd
    - teleport_kubernetes_dynamic

- name: Rbac the Teleport host
  hosts: teleport
  vars:
    teleport_semaphore_auth_host: teleport
    teleport_semaphore_auth_host_type: node
  roles:
    - util_common
    - teleport_rbac_bootstrap
