---
- name: Terraform run
  hosts: localhost
  become: false
  roles:
    - tf_simple

- name: Teleport cluster and agents setup
  hosts:
    - teleport
    - nodes_ssh_agent
    - nodes_ssh_agentless
  roles:
    - teleport_lib
    - common
    - teleport
    - teleport_ssh_agent
    - teleport_ssh_agentless
    # - teleport_ssh_agentless_simple # Broken on most distros

- name: Teleport RBAC Bootstrap
  hosts: teleport
  roles:
    - teleport_lib
    - teleport_rbac_bootstrap
