---
- name: Terraform run
  hosts: localhost
  become: false
  roles:
    - tf_kubernetes_dynamic

- name: Teleport host setup
  hosts: teleport, teleport_kubernetes_dynamic
  roles:
    - teleport_lib
    - common
    - teleport
    - k3s_install
    - teleport_kubernetes_crd
    - teleport_kubernetes_dynamic
    - teleport_rbac_bootstrap
