---
# Teleport cluster installed on a single VM, and a K3s cluster with teleport-kube-agent installed

- name: Terraform run
  hosts: localhost
  become: false
  roles:
    - tf_teleport_kube

- name: K3s install
  hosts:
    - nodes_k3s_teleport_cluster
    - nodes_k3s_teleport_agent
  roles:
    - teleport_lib
    - k3s_install

- name: Helm install teleport-cluster
  hosts: nodes_k3s_teleport_cluster
  roles:
    - teleport_lib
    - teleport_cluster_helm

- name: Helm install teleport-kube-agent
  hosts:
    - nodes_k3s_teleport_agent
  roles:
    - teleport_lib
    - teleport_kube_agent_helm

- name: Reset teleport-admin user
  hosts: nodes_k3s_teleport_cluster
  roles:
    - teleport_lib
  tasks:
    - name: Sleep 20 seconds
      ansible.builtin.pause:
        seconds: 20
    - name: Reset teleport-admin user
      changed_when: true
      ansible.builtin.command:
        cmd: kubectl exec -n teleport-cluster -ti deployment/teleport-cluster-auth -- tctl users reset teleport-admin
