[project]
name = "lab-teleport"
version = "0.1.3"
requires-python = ">=3.13"
# Check latest ansible version: https://docs.ansible.com/projects/ansible/latest/reference_appendices/release_and_maintenance.html
dependencies = ["ansible<14", "cryptography", "jmespath", "kubernetes"]

[dependency-groups]
dev = ["ansible-lint"]

[tool.uv]
package = false

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
