---
- name: Check if helm exists
  failed_when: false
  changed_when: false
  register: helm_exists
  ansible.builtin.command:
    cmd: which helm

- name: Download the Helm install script
  when: helm_exists.rc != 0
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /root/get_helm.sh
    mode: '0700'

- name: Install Helm
  when: helm_exists.rc != 0
  changed_when: true
  register: teleport_install
  until: "teleport_install is not failed"
  retries: 30
  delay: 1
  ansible.builtin.command:
    cmd: /root/get_helm.sh


- name: Grab the JWKS
  changed_when: false
  register: jwks
  ansible.builtin.command:
    cmd: kubectl get --raw /openid/v1/jwks

- name: Cluster tasks
  delegate_to: teleport-k3s-cluster-1
  block:
    - name: Create the Teleport join token using CRs
      kubernetes.core.k8s:
        template: k8s-cr-teleport-join-token.yaml.j2

- name: Deploy teleport-kube-agent helm chart
  kubernetes.core.helm:
    name: teleport-kube-agent
    chart_repo_url: https://charts.releases.teleport.dev/
    chart_ref: teleport-kube-agent
    chart_version: "{{ teleport_version }}"
    release_namespace: teleport-kube-agent
    create_namespace: true
    values: "{{ lookup('template', 'values-teleport-kube-agent.yaml.j2') | from_yaml }}"

- name: Install the hello-world helm chart
  kubernetes.core.helm:
    name: hello-world
    chart_repo_url: https://helm.github.io/examples
    chart_ref: hello-world
    release_namespace: hello-world
    create_namespace: true
