all:
  vars:
    # Override these variables in `group_vars/all/main.yml`
    ansible_ssh_private_key_file: "~/.ssh/YOURKEY"
    e_mail: you@example.com
    lego_path: /etc/lego
    lego_path_local: /root/lego
    user_local: my_username # Must be your actual username
    user_remote: my_username # Username on the terraform-provisioned system
    domain_name: teleport.example.com
    teleport_version: 17.3.0
    teleport_fips: false
    terraform_cloud_image: /path/to/a/cloud-image.qcow2 # or .img
    letsencrypt_working_environment_choice: staging # `staging` or `prod`
    letsencrypt_lego_type: cloudflare # See supported providers here: https://go-acme.github.io/lego/dns/
    letsencrypt_lego_env_vars: # Cloudflare example below. See supported providers here: https://go-acme.github.io/lego/dns/
      CLOUDFLARE_EMAIL: you@example.com
      CLOUDFLARE_DNS_API_TOKEN: /path/to/my/token.txt
    helm_teleport_cluster_lb_mode: L4 # L4 or L7 Kubernetes Load Balancer. Sets TCPRoute versus IngressRoute respectively (traefik)

    # Variables below should not be changed unless you know what you are doing
    letsencrypt_working_environment:
      staging: https://acme-staging-v02.api.letsencrypt.org/directory
      prod: https://acme-v02.api.letsencrypt.org/directory
    lego_package_os_map:
      Fedora: golang-github-acme-lego
      Ubuntu: lego
      MacOSX: lego
      Archlinux: lego
    ssh_name_map:
      Debian: ssh
      RedHat: sshd

# Groups and hosts section which you might need to edit for your needs
ungrouped:
  hosts:
    teleport:
      ansible_host: 192.168.0.160 # same as kube-cluster
    kubernetes:
      ansible_host: 192.168.0.171

nodes_ssh_agent:
  hosts:
    teleport-node-1:
      ansible_host: 192.168.0.201
    teleport-node-2:
      ansible_host: 192.168.0.202

nodes_ssh_agentless:
  hosts:
    teleport-node-agentless-1:
      ansible_host: 192.168.0.211
    teleport-node-agentless-2:
      ansible_host: 192.168.0.212

teleport_kubernetes_dynamic:
  hosts:
    teleport-kubernetes-dynamic-1:
      ansible_host: 192.168.0.210

nodes_k3s_teleport_cluster:
  hosts:
    teleport-k3s-cluster-1:
      ansible_host: 192.168.0.160 # Same as single-vm teleport instance

nodes_k3s_teleport_agent:
  hosts:
    teleport-k3s-agent-1:
      ansible_host: 192.168.0.214
    teleport-k3s-agent-2:
      ansible_host: 192.168.0.215
