ungrouped:
  hosts:
    teleport:
      ansible_host: 192.168.0.160
    kubernetes:
      ansible_host: 192.168.0.171

ssh_nodes:
  hosts:
    test1:
      ansible_host: 192.168.0.201
    test2:
      ansible_host: 192.168.0.202
    test3:
      ansible_host: 192.168.0.203

all:
  vars:
    # Please override these variables in `group_vars/all/main.yml`
    ansible_ssh_private_key_file: "~/.ssh/YOURKEY"
    e_mail: you@example.com
    lego_path: /etc/lego
    lego_path_local: /root/lego
    lego_user_local: my_username # Must be your actual username
    lego_user_remote: my_username # Must be a username as provisioned by terraform
    domain_name: teleport.example.com
    teleport_version: 15.3.5
    letsencrypt_env_choice: staging # `staging` or `prod`

    # Variables below should not be changed unless you know what you are doing
    letsencrypt_env:
      staging: https://acme-staging-v02.api.letsencrypt.org/directory
      prod: https://acme-v02.api.letsencrypt.org/directory
