ungrouped:
  hosts:
    teleport:
      ansible_host: 192.168.0.160
    kubernetes:
      ansible_host: 192.168.0.171

nodes_ssh:
  hosts:
    teleport-node-1:
      ansible_host: 192.168.0.201
    teleport-node-2:
      ansible_host: 192.168.0.202

nodes_ssh_agentless:
  hosts:
    teleport-node-agentless-1:
      ansible_host: 192.168.0.203
    teleport-node-agentless-2:
      ansible_host: 192.168.0.204

teleport_kubernetes_dynamic:
  hosts:
    teleport-kubernetes-dynamic-1:
      ansible_host: 192.168.0.210

all:
  vars:
    # Please override these variables in `group_vars/all/main.yml`
    ansible_ssh_private_key_file: "~/.ssh/YOURKEY"
    e_mail: you@example.com
    lego_path: /etc/lego
    lego_path_local: /root/lego
    user_local: my_username # Must be your actual username
    user_remote: my_username # Username on the terraform-provisioned system
    domain_name: teleport.example.com
    teleport_version: 16.2.0
    letsencrypt_env_choice: staging # `staging` or `prod`
    terraform_cloud_image: /path/to/a/cloud-image.qcow2 # or .img

    # Variables below should not be changed unless you know what you are doing
    letsencrypt_env:
      staging: https://acme-staging-v02.api.letsencrypt.org/directory
      prod: https://acme-v02.api.letsencrypt.org/directory
