- name: End play if terraform_destroy variable is set to any value other than false
  when: terraform_destroy | default(false)
  ansible.builtin.meta: end_play

- name: Wait 600 seconds for target connection to become reachable/usable
  ansible.builtin.wait_for_connection:
    delay: "{{ conn_wait_first_run | default(true) | ternary(5, 0) }}" # Delay 5 seconds on first run, otherwise don't delay

- name: Set the conn_wait_first_run to false
  ansible.builtin.set_fact:
    conn_wait_first_run: false

- name: Gather facts for first time
  retries: 300
  delay: 1
  ansible.builtin.setup:

- name: Wait for cloud init to finish
  community.general.cloud_init_data_facts:
    filter: status
  register: cloud_init_state
  until: "cloud_init_state.cloud_init_data_facts.status.v1.stage is defined and not cloud_init_state.cloud_init_data_facts.status.v1.stage"
  retries: 120
  delay: 1
