- name: Include the semaphore role
  ansible.builtin.include_role:
    name: teleport_semaphore

- name: Set up vnet
  delegate_to: "{{ teleport_semaphore_executor }}"
  run_once: true
  block:
    - name: Create vnet config
      ansible.builtin.copy:
        dest: /root/vnet-config.yaml
        mode: "0644"
        owner: root
        group: root
        content: |
          kind: vnet_config
          version: v1
          metadata:
            name: vnet-config
          spec:
            custom_dns_zones:
            - suffix: {{ teleport_vnet_domain_name }}

    - name: Apply vnet
      changed_when: true
      ansible.builtin.shell:
        cmd: "set -o pipefail && cat /root/vnet-config.yaml | {{ teleport_semaphore_exec_prefix }} tctl create -f"

## Below block is for VM. TODO: Branch off for kube app
- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Enable and start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Add app config block
  notify: "Restart Teleport"
  ansible.builtin.blockinfile:
    path: /etc/teleport.yaml
    content: |
      app_service:
        enabled: true
        debug_app: false
        # mcp_demo_server: false
        # resources:
        #   - labels:
        #       "*": "*"
        apps:
          - name: "nginx-{{ inventory_hostname }}"
            uri: "tcp://localhost:80"
            labels:
              env: "prod"
          - name: "nginx-vnet-{{ inventory_hostname }}"
            uri: "tcp://localhost:80"
            public_addr: "nginx-vnet-{{ inventory_hostname }}.{{ teleport_vnet_domain_name }}"
            labels:
              env: "prod"
