- name: Search-replace
  loop: "{{ teleport_install_repos.stdout_lines }}"
  ansible.builtin.replace:
    dest: "{{ item }}"
    regexp: "{{ outer_item['regexp'] }}"
    replace: "{{ outer_item['replace'] }}"
