- name: Install yum-util
  ansible.builtin.package:
    name: yum-utils

- name: Get url
  ansible.builtin.get_url:
    url: "https://yum.releases.teleport.dev/{{ os_release_id }}/{{ ansible_distribution_major_version }}/\
      Teleport/{{ ansible_architecture }}/{{ teleport_channel }}/teleport.repo"
    dest: /etc/yum.repos.d/teleport.repo
    mode: "0644"

- name: Install Teleport-FIPS
  ansible.builtin.package:
    name: teleport-ent-fips
    state: present
