---
- name: Create temp directory
  ansible.builtin.tempfile:
    state: directory
  register: teleport_install_tempdir

- name: Download and extract tarball from upstream Teleport URL
  ansible.builtin.unarchive:
    src: "https://cdn.teleport.dev/teleport-update-v{{ teleport_version }}-linux-amd64-bin.tar.gz" # TODO support different arch
    dest: "{{ teleport_install_tempdir.path }}"
    remote_src: true

- name: Install Teleport
  changed_when: true
  ansible.builtin.command:
    cmd: "{{ teleport_install_tempdir.path }}/teleport/teleport-update enable --proxy {{ domain_name }}"

- name: Delete temp directory
  ansible.builtin.file:
    path: "{{ teleport_install_tempdir.path }}"
    state: absent
