- name: Install yum-util
  ansible.builtin.package:
    name: yum-utils

- name: Get url
  ansible.builtin.get_url:
    url:
      "https://yum.releases.teleport.dev/{{ teleport_install_os_release_id }}/{{ ansible_facts.distribution_major_version }}/\
      Teleport/{{ ansible_architecture }}/{{ teleport_install_channel }}/teleport.repo"
    dest: /etc/yum.repos.d/teleport.repo
    mode: "0644"

- name: Install Teleport-FIPS
  ansible.builtin.package:
    name: teleport-ent-fips
    state: present
