- name: Set the teleport_channel fact
  ansible.builtin.set_fact:
    teleport_channel: "v{{ teleport_version | regex_findall('^(\\d+)\\.') }}" # For example v17

- name: Fips or script install
  ansible.builtin.include_tasks:
    file: "{{ teleport_fips | ternary('fips-install.yml', 'script-install-' ~ ansible_distribution | lower ~ '.yml') }}" # For example fips-install-centos.yml
