---
- name: Disable the tmpfs /tmp mount
  # We need to disable this on systems with small amounts of ram
  # when: ansible_distribution == "Fedora" # And Ubuntu 26.04
  retries: 10
  delay: 1
  failed_when: false # Some OSs don't have this and will fail
  ansible.builtin.service:
    name: tmp.mount
    state: stopped
    enabled: false

- name: Check if teleport exists
  failed_when: false
  changed_when: false
  register: teleport_exists
  ansible.builtin.command:
    cmd: which teleport

- name: If teleport not found
  when: teleport_exists.rc != 0
  block:
    - name: Stat teleport systemd service file
      register: teleport_systemd_service_file
      ansible.builtin.stat:
        path: /etc/systemd/system/teleport.service

    - name: Non-agent or agent without updater
      when: not install_via_updater or not teleport_install_teleport_agent
      block:
        - name: Import tarball installer (used if oneliner broken)
          when: install_via_tarball
          ansible.builtin.import_tasks:
            file: install-tarball.yml

        - name: Import oneliner installer (default)
          when: not install_via_tarball
          ansible.builtin.import_tasks:
            file: install-oneliner.yml

    - name: Agent AND install_via_updater enabled (desired for agents)
      when: install_via_updater and teleport_install_teleport_agent
      ansible.builtin.import_tasks:
        file: install-updater.yml

    - name: Centos and Rocky PATH override block
      # For some reason those cloud distros don't have `/usr/local/bin` in the PATH....
      when: |
        ansible_distribution == "CentOS"
        or ansible_distribution == "Rocky"
      block:
        - name: Add path to /etc/environment
          notify: Reset SSH Connection
          ansible.builtin.lineinfile:
            dest: /etc/environment
            state: present
            regexp: '^PATH=\/usr\/local\/bin'
            line: "PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin"

    - name: Install the systemd file when needed
      when: not teleport_systemd_service_file.stat.exists
      changed_when: true
      ansible.builtin.command: teleport install systemd -o /etc/systemd/system/teleport.service
