- name: Wait for Teleport to become ready
  ansible.builtin.uri:
    url: "https://{{ domain_name }}/webapi/ping"
    return_content: true
  register: util_wait_teleport_ready_url_response
  until:
    - util_wait_teleport_ready_url_response.status == 200
    - util_wait_teleport_ready_url_response.json is defined
    - util_wait_teleport_ready_url_response.json.cluster_name == domain_name
  failed_when: >
    util_wait_teleport_ready_url_response.status not in [200] or
    (util_wait_teleport_ready_url_response.status == 200 and
     util_wait_teleport_ready_url_response.json is defined and
     util_wait_teleport_ready_url_response.json.cluster_name not in [domain_name])
  retries: 600
  delay: 0
