- name: Disable the tmpfs /tmp mount
  when: ansible_facts['distribution'] == "Fedora"
  ansible.builtin.service:
    name: tmp.mount
    state: stopped
    enabled: false

- name: Check if teleport exists
  failed_when: false
  changed_when: false
  register: teleport_exists
  ansible.builtin.command:
    cmd: which teleport


- name: Download the Teleport install script
  ansible.builtin.get_url:
    url: https://goteleport.com/static/install.sh
    dest: /root/teleport_install.sh
    mode: '0755'

- name: Install teleport
  when: teleport_exists.rc != 0
  changed_when: true
  register: teleport_install
  until: "teleport_install is not failed"
  retries: 30
  delay: 1
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: /root/teleport_install.sh {{ teleport_version }} enterprise


- name: Stat teleport systemd service file
  register: teleport_systemd_service_file
  ansible.builtin.stat:
    path: /etc/systemd/system/teleport.service

- name: Install the systemd file when needed
  when: not teleport_systemd_service_file.stat.exists
  changed_when: true
  ansible.builtin.command: teleport install systemd -o /etc/systemd/system/teleport.service
