- name: Disable the tmpfs /tmp mount
  # We need to disable this on systems with small amounts of ram
  when: ansible_facts['distribution'] == "Fedora"
  retries: 10
  delay: 1
  ansible.builtin.service:
    name: tmp.mount
    state: stopped
    enabled: false

- name: Check if teleport exists
  failed_when: false
  changed_when: false
  register: teleport_exists
  ansible.builtin.command:
    cmd: which teleport

- name: Download the Teleport install script
  ansible.builtin.get_url:
    # URL example: /tmp/teleport-YQf9rzNvEV/teleport-v16.4.12-linux-amd64-bin.tar.gz
    url: "https://cdn.teleport.dev/install-v{{ teleport_version }}.sh"
    # Checksum example: //cdn.teleport.dev/teleport-ent-v16.4.12-linux-amd64-bin.tar.gz.sha256
    checksum: "sha256:{{ lookup('ansible.builtin.url', 'https://cdn.teleport.dev/install-v' + teleport_version + '.sh.sha256').split('  ')[0] }}"
    dest: /root/teleport_install.sh
    mode: '0755'

- name: Patch for distros which don't have a repo
  # https://github.com/gravitational/teleport/pull/51036
  ansible.builtin.lineinfile:
    path: /root/teleport_install.sh
    search_string: '  $SUDO "$TEMP_DIR/teleport/install"'
    line: '  $SUDO "$TEMP_DIR/teleport${TELEPORT_SUFFIX}/install"'

- name: Centos 8 fix
  # https://serverfault.com/questions/1161816/mirrorlist-centos-org-no-longer-resolve
  when:
    - ansible_distribution=="CentOS"
    - ansible_distribution_major_version=="8"
  block:
    - name: Get repo names
      changed_when: false
      ansible.builtin.command:
        cmd: "find /etc/yum.repos.d/ -type f -name 'CentOS-*.repo'"
      register: repos

    - name: Outer loop
      loop:
        - regexp: "mirror.centos.org"
          replace: "vault.centos.org"
        - regexp: "^#.*baseurl=http"
          replace: "baseurl=http"
        - regexp: "^mirrorlist=http"
          replace: "#mirrorlist=http"
      loop_control:
        loop_var: outer_item
      ansible.builtin.include_tasks:
        file: centos-8-search-replace.yml

- name: Centos and Rocky PATH override block
  # For some reason those cloud distros don't have `/usr/local/bin` in the PATH....
  when: |
    ansible_facts['distribution'] == "CentOS"
    or ansible_facts['distribution'] == "Rocky"
  block:
    - name: Add path to /etc/environment
      notify: Reset SSH Connection
      ansible.builtin.lineinfile:
        dest: /etc/environment
        state: present
        regexp: '^PATH=\/usr\/local\/bin'
        line: 'PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin'

- name: Block for hosts requiring Teleport installed
  when:
    - teleport_exists.rc != 0
    - >
      inventory_hostname == "teleport"
      or 'nodes_ssh_agent' in group_names
      or 'teleport_kubernetes_dynamic' in group_names
  block:
    - name: Install teleport
      changed_when: true
      register: teleport_install
      until: "teleport_install is not failed"
      retries: 4
      delay: 1
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: "/root/teleport_install.sh {{ teleport_version }} enterprise"

    - name: Stat teleport systemd service file
      register: teleport_systemd_service_file
      ansible.builtin.stat:
        path: /etc/systemd/system/teleport.service

    - name: Install the systemd file when needed
      when: not teleport_systemd_service_file.stat.exists
      changed_when: true
      ansible.builtin.command: teleport install systemd -o /etc/systemd/system/teleport.service
