- name: Terraform run
  community.general.terraform:
    project_path: '{{ role_path }}/tf'
    state: "{{ terraform_destroy | default(false) | ternary('absent', 'present') }}"
    lock: false
    complex_vars: false
    variables:
      public_key: "{{ ansible_ssh_private_key_file }}.pub"
      cloud_image: "{{ terraform_cloud_image }}"
      login_username: "{{ user_remote }}"
    force_init: true
