---
- name: Include the teleport_semaphore role
  ansible.builtin.include_role:
    name: teleport_semaphore

- name: Stat the teleport token file
  register: teleport_token_file
  ansible.builtin.stat:
    path: /etc/teleport.token

- name: If teleport token file does not exist
  when: not teleport_token_file.stat.exists
  block:
    - name: Set random token value
      ansible.builtin.set_fact:
        token: "{{ 999999999999999999999999999999999999999999999999999999999999999999 | random | to_uuid }}"

    - name: Issue node token
      changed_when: true
      delegate_to: "{{ teleport_executor }}"
      ansible.builtin.command:
        cmd: "{{ teleport_exec_prefix }} tctl tokens add --type=node --value {{ token }}"

    - name: Place token file
      ansible.builtin.copy:
        dest: /etc/teleport.token
        content: "{{ token }}"
        mode: "0600"
        owner: root
        group: root

    - name: Include the teleport_install role
      ansible.builtin.include_role:
        name: teleport_install

    - name: Join node
      changed_when: true
      notify: Restart Teleport # teleport_lib role required in play
      ansible.builtin.command:
        cmd: >
          teleport node configure
            --output file:///etc/teleport.yaml
            --token /etc/teleport.token
            --proxy {{ domain_name }}:443
            --labels hostname={{ ansible_hostname }}
            --labels commonkey=commonvalue
