---
- name: Renew the cert
  delegate_to: 127.0.0.1
  connection: local
  run_once: true
  changed_when: true
  become: false
  environment: "{{ letsencrypt_lego_env_vars }}"
  ansible.builtin.command:
    cmd: >
      lego
          --server "{{ letsencrypt_working_environment[letsencrypt_working_environment_choice] }}"
          --email "{{ e_mail }}"
          --path "{{ lego_path_local }}"
          --dns "{{ letsencrypt_lego_type }}"
          --domains '*.{{ domain_name }}'
          renew --days 10

- name: Create cert dir
  ansible.builtin.file:
    path: "{{ lego_path }}"
    state: directory
    mode: "0700"

- name: Slurp the cert/key and license files
  delegate_to: 127.0.0.1
  become: false
  register: slurped_files
  vars:
    lego_file_mapping:
      - local_file: "{{ lego_path_local }}/certificates/_.{{ domain_name }}.crt"
      - local_file: "{{ lego_path_local }}/certificates/_.{{ domain_name }}.key"
      - local_file: "{{ playbook_dir }}/license.pem"
  loop: "{{ lego_file_mapping }}"
  ansible.builtin.slurp:
    src: "{{ item.local_file }}"

- name: Create the Teleport namespaces
  kubernetes.core.k8s:
    template: k8s-namespace-teleport-cluster.yaml.j2

- name: Create the License secret
  kubernetes.core.k8s:
    template: k8s-secret-license.yaml.j2

- name: Create the Teleport HTTPS secret
  kubernetes.core.k8s:
    template: k8s-secret-https.yaml.j2

- name: Deploy teleport-cluster helm chart
  kubernetes.core.helm:
    name: teleport-cluster
    chart_repo_url: https://charts.releases.teleport.dev/
    chart_ref: teleport-cluster
    chart_version: "{{ teleport_version }}"
    release_namespace: teleport-cluster
    create_namespace: true
    values: "{{ lookup('template', 'values-teleport-cluster.yaml.j2') | from_yaml }}"

- name: Create the traefik resources for teleport-cluster (L4 or L7 load balancer)
  kubernetes.core.k8s:
    template: "k8s-traefik-{{  helm_teleport_cluster_lb_mode | upper }}.yaml.j2"

- name: Create the Teleport join token using CRs
  kubernetes.core.k8s:
    template: k8s-cr-teleport-join-token.yaml.j2

- name: Deploy teleport-kube-agent helm chart
  kubernetes.core.helm:
    name: teleport-kube-agent
    chart_repo_url: https://charts.releases.teleport.dev/
    chart_ref: teleport-kube-agent
    chart_version: "{{ teleport_version }}"
    release_namespace: teleport-kube-agent
    create_namespace: true
    values: "{{ lookup('template', 'values-teleport-kube-agent.yaml.j2') | from_yaml }}"
